var id = {
  'PASSPORT_FRONT': 1,
  'BIOMETRIC_RESIDENCE_PERMIT_FRONT': 2,
  'BIOMETRIC_RESIDENCE_PERMIT_BACK': 3,
  'PREVIOUS_UK_VISA': 4,
  'PASSPORT_FRONT_TWO': 5,
  'CURRENT_COUNTRY_RESIDENCE_PERMIT': 6
};

module.exports = id;
